### ISSUE TITLE
Disabling stage rendering (L+dpad right) doesn't hide gr2 models

### ISSUE THREAD

**Issue by markymawk** [EonTAS/DebugMode#1]
Can be tested on Training Room or Frigate Orpheon

(great work btw :] )

**Comment by EonTAS** [comment]
sadly dont have enough fine control to disable just those with the stage toggle. That model type is also what toggles the display of special items e.g. beam sword, assist trophy,  food, starman, lightning, warpstar, star rod, goey bomb, freezie, hothead, team healer, screw attack

so i felt that its better to be attached to the fighter model toggle since thats intended to disable everything except the stage render.
